export const units = [
  { label: 'None', value: 'none' },
  { label: 'BAGS (Bag)', value: 'Bag' },
  { label: 'BOX (Box)', value: 'Box' },
  { label: 'BUNDLES (Bdl)', value: 'Bdl' },
  { label: 'CANS (Can)', value: 'Can' },
  { label: 'CARTONS (Ctn)', value: 'Ctn' },
  { label: 'DOZENS (Dzn)', value: 'Dzn' },
  { label: 'GRAMMES (Gm)', value: 'Gm' },
  { label: 'KILOGRAMS (Kg)', value: 'Kg' },
  { label: 'LITRE (Ltr)', value: 'Ltr' },
  { label: 'METERS (Mtr)', value: 'Mtr' },
  { label: 'MILLILITRE (Ml)', value: 'Ml' },
  { label: 'NUMBERS (Nos)', value: 'Nos' },
  { label: 'PACKS (Pac)', value: 'Pac' },
  { label: 'PAIRS (Prs)', value: 'Prs' },
  { label: 'PIECES (Pcs)', value: 'Pcs' },
  { label: 'QUINTAL (Qtl)', value: 'Qtl' },
  { label: 'ROLLS (Rol)', value: 'Rol' },
  { label: 'SQUARE FEET (Sqf)', value: 'Sqf' },
  { label: 'SQUARE METER (Sqm)', value: 'Sqm' },
  { label: 'SQUARE INCH (Sqin)', value: 'Sqin' },
  { label: 'CUBIC METER (Cum)', value: 'Cum' },
  { label: 'CUBIC FEET (Cft)', value: 'Cft' },
  { label: 'TONNES (Tons)', value: 'Tons' },
  { label: 'GRAM (g)', value: 'g' },
  { label: 'MILLIGRAM (mg)', value: 'mg' },
  { label: 'INCHES (In)', value: 'In' },
  { label: 'CENTIMETER (Cm)', value: 'Cm' },
  { label: 'FOOT (Ft)', value: 'Ft' },
  { label: 'YARD (Yd)', value: 'Yd' },
  { label: 'HECTARE (Ha)', value: 'Ha' },
  { label: 'ACRE (Acre)', value: 'Acre' },
  { label: 'SET (Set)', value: 'Set' },
  { label: 'BOTTLES (Btl)', value: 'Btl' },
  { label: 'TUBE (Tube)', value: 'Tube' },
  { label: 'JAR (Jar)', value: 'Jar' },
  { label: 'BOXES (Boxes)', value: 'Boxes' },
  { label: 'CASE (Case)', value: 'Case' },
  { label: 'TRAY (Tray)', value: 'Tray' },
  { label: 'PACKET (Pkt)', value: 'Pkt' },
  { label: 'SACHET (Sachet)', value: 'Sachet' }
]
